
modLoader="javafml" #mandatory

loaderVersion="[40,)" #mandatory This is typically bumped every Minecraft version by Forge. See our download page for lists of versions.

license="ARR"

[[mods]] #mandatory

modId= "suppsquared" #mandatory

version = "${version}"

displayName="Supplementaries Squared" #mandatory

logoFile="icon.png" #optional

credits="Mehvahdjukaar, Plantkillable" #optional

authors="MehVahdJukaar, Plantkillable" #optional

description='''
Additional blocks for Supplementaries
'''


[modproperties.suppsquared]
    catalogueItemIcon = "suppsquared:suppsqaured_sack_lime" #catalogue icon


[[dependencies.suppsquared]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[40,)" #mandatory
    ordering="NONE"
    side="BOTH"

[[dependencies.suppsquared]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2,1.20)"
    ordering="NONE"
    side="BOTH"

[[dependencies.suppsquared]]
    modId="moonlight"
    mandatory=true
    versionRange="[1.19.2-2.2.25,]"
    side="BOTH"

[[dependencies.suppsquared]]
    modId="supplementaries"
    mandatory=true
    versionRange="[1.19.2-2.2.61,]"
    side="BOTH"
    ordering="AFTER"